// <auto-generated />
namespace CourseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class commentcreativeIdfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentcreativeIdfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201603171244493_comment creativeId fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
