// <auto-generated />
namespace CourseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class compose2storages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(compose2storages));
        
        string IMigrationMetadata.Id
        {
            get { return "201603171237585_compose 2 storages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
